language: cpp
sudo: required


before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get -qq update
- sudo apt-get install -qq -y cmake libboost-test1.55-dev g++-6 libgcc-6-dev

before_script:
- mkdir build
- cd build
- CXX=g++-6 cmake ..

script:
    - make -j2
    - ctest
